wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.entry_search, name="entry_search"),
    path("random_page", views.random_page, name="random_page"),
    path("wiki/<str:title>", views.view_entry, name="view_entry"),
    path("create", views.create_new_page, name="create_new_page"),
    path("edit/<str:title>", views.edit_page, name="edit_page")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
from . import util
import markdown2
import random

# Form for searching the encyclopedia
class NewSearchForm(forms.Form):
    entry_search = forms.CharField(label="Search Encyclopedia")

# Form for creating a new entry in the encylopedia
class NewCreateForm(forms.Form):
    title = forms.CharField(label="Page Title", widget=forms.TextInput(attrs={'class' : 'form-control form-control-lg'}))
    markdown_content = forms.CharField(label = "Markdown Content", widget=forms.Textarea(attrs={'class' : 'form-control'}))

# Form for editing an entry in the encyclopedia
class NewEditForm(forms.Form):
    markdown_content = forms.CharField(label = "Markdown Content", widget=forms.Textarea(attrs={'class' : 'form-control'}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "search_form": NewSearchForm()
    })

def view_entry(request, title):
    entry = util.get_entry(title)

    # Entry with this title does not exist
    if entry is None:
        return render(request, "encyclopedia/entry.html", {
        "entry": None,
        "title": title.capitalize(),
        "search_form": NewSearchForm()
        })

    # Entry with this title exists
    else:
        return render(request, "encyclopedia/entry.html", {
            "entry": markdown2.markdown(entry),
            "title": title.capitalize(),
            "search_form": NewSearchForm()
        })
   
# Search for an existing entry in the encyclopedia
def entry_search(request):
    # Check if method is POST
    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = NewSearchForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the search word from the 'cleaned' version of form data
            search_keyword = form.cleaned_data["entry_search"]

            # See if search word matches any of the entry titles exactly
            all_entries = util.list_entries()
            
            # Check for exact matches
            if search_keyword.upper() in (entry.upper() for entry in all_entries):
                # Keyword matches exactly, redirect to that page
                return redirect('/wiki/' + search_keyword)
    
            # Check for partial matches
            entry_subset = []
            for entry in all_entries:
                if search_keyword.upper() in entry.upper():
                    entry_subset.append(entry)
            
            if len(entry_subset) > 0: # We have some partial matches
                return render(request, "encyclopedia/search_results.html", {
                    "entries": entry_subset,
                    "search_form": NewSearchForm()
                })
                        
            # No matches
            return render(request, "encyclopedia/search_results.html", {
                    "entries": None,
                    "search_form": NewSearchForm()
                })

        else:
            # If the form is invalid, re-render the page with existing information.
            return render(request, "encyclopedia/index.html", {
                "search_form": form
            })

    return render(request, "encyclopedia/index.html", {
        "search_form": NewSearchForm()
    })

# Take user to random encyclopedia entry
def random_page(request):
    # Find all current encyclopedia entries
    all_entries = util.list_entries()
    # Pull random entry title
    random_entry_title = random.choice(all_entries)
    # Display entry
    #return view_entry(request, random_entry_title)
    return redirect('/wiki/' + random_entry_title)

# Create a new encyclopedia entry
def create_new_page(request):
    if request.method == "POST":
        # Take in the data the user submitted and save it as form
        form = NewCreateForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the title and markdown content
            title = form.cleaned_data["title"].capitalize()
            markdown_content = form.cleaned_data["markdown_content"]

            # Entry does not yet exist
            if util.get_entry(title) is None:
                # Save entry and bring user to the new entry's page
                util.save_entry(title, markdown_content)
                return redirect("/wiki/" + title)

            # If entry already exists, present user with error message
            else:
                return render(request, "encyclopedia/error.html", {
                    "message": "An encyclopedia entry already exists under this title",
                    "search_form": NewSearchForm()
                })
        
        else:
            # If the form is invalid, re-render the page with existing information.
            return render(request, "encyclopedia/create.html", {
                "create_form": form,
                "search_form": NewSearchForm()
            })
        

    else:
        return render(request, "encyclopedia/create.html", {
            "create_form": NewCreateForm(),
            "search_form": NewSearchForm()
        })

# Lets used edit entry's markdown content
def edit_page(request, title):
    markdown_content = util.get_entry(title)

    # Check if request method is post
    if request.method == "POST":
        # Take in the data the user submitted and save it as form
        form = NewEditForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the markdown content
            markdown_content = form.cleaned_data["markdown_content"]

            # Save entry and bring user to the entry's page
            util.save_entry(title, markdown_content)
            return redirect("/wiki/" + title)
        
        else:
            # If the form is invalid, re-render the page with existing information.
            return render(request, "encyclopedia/edit.html", {
            "edit_form": form,
            "search_form": NewSearchForm(),
            "title": title
        })
        

    else:
        return render(request, "encyclopedia/edit.html", {
            "edit_form": NewEditForm({'markdown_content': markdown_content}),
            "search_form": NewSearchForm(),
            "title": title
        })

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>

    <div class="form-group col-md-11">
        <form action="{% url 'encyclopedia:create_new_page'%}" method="post">
            {% csrf_token %}
            {{ create_form }}
            <br>
            <button type="submit" class="btn btn-primary">Save New Page</button>
        </form>
    </div>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page: {{ title }}
{% endblock %}

{% block body %}
    <h1>Edit Page: {{ title }}</h1>

    <div class="form-group col-md-11">
        <form action="{% url 'encyclopedia:edit_page' title=title %}" method="post">
            {% csrf_token %}
            {{ edit_form }}
            <br>
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </form>
    </div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia Entry: {{ title }}
{% endblock %}

{% block body %}
    {% if entry is None %}
    <h1>Error: requested page cannot be found</h1>
    {% else %}
    <div>{{ entry |safe}}</div>

    <a href="{% url 'encyclopedia:edit_page' title=title %}" class="btn btn-warning">Edit Page</a>
    
    {% endif %}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>Error: {{ message }}</h1>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="{% url 'encyclopedia:view_entry' title=entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>

                <form action="{% url 'encyclopedia:entry_search'%}" method="post">
                    {% csrf_token %}
                    {{ search_form }}
                </form>

                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create_new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    {% if entries is None %}
    <h1>Error: Your query does not match any of the encyclopedia entries</h1>
    {% else %}
    <h1>Search Results</h1>
    <ul>
        {% for entry in entries %}
            <a href="{% url 'encyclopedia:view_entry' title=entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>
    {% endif %}

{% endblock %}